export default {
    CREATE_USER:'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    //como seria mas correcto? SAVE USER PREFERENCE? O SAVE PREFERENCE?
    //SAVE_PREFERENCE: 'SAVE_PREFERENCE',
    LOAD_RECIPE:'LOAD_RECIPE',
    UPDATE_RECIPE:'UPDATE_RECIPE'
}