export default {
    CREATE_USER:'CREATE_USER',
    UPLOAD_USER: 'UPLOAD_USER',
    //como seria mas correcto? SAVE USER PREFERENCE? O SAVE PREFERENCE?
    SAVE_PREFERENCE: 'SAVE_PREFERENCE',
    LOAD_RECIPE:'LOAD_RECIPE',
    UPLOAD_RECIPE:'UPLOAD_RECIPE',

}