export default {
	SIGN_IN: 'SIGN_IN',
	LOAD_USER: 'LOAD_USER',
	CREATE_USER: 'CREATE_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	LOAD_PRODUCTS: 'LOAD_PRODUCTS',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	LOAD_CART: 'LOAD_CART',
	UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
	DELETE_CART_ITEM: 'DELETE_CART_ITEM',
	ADD_NUMBER_CART: 'ADD_NUMBER_CART'
};
