export default {
  LOAD_QUESTION: 'LOAD_QUESTION',
  LOAD_PROJECT: 'LOAD_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  SAVE_ANSWER: 'SAVE_ANSWER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER_PROJECT: 'REGISTER_PROJECT',
  SAVE_USER: 'SAVE_USER',
  GET_USER: 'GET_USER',
  REMOVE_USER: 'REMOVE_USER',
  GET_SCORES: 'GET_SCORES'
}