export default {
	CREATE_USER: 'CREATE_USER',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	/////////////Film Store/////////////////
	SEARCH_FILM: 'SEARCH_FILM',
	SLIDER_FILM: 'SLIDER_FILM',
	POPULAR_FILM: 'POPULAR_FILM',
	COMING_SOON_FILM: 'COMING_SOON_FILM',
	ADD_FAV: 'ADD_FAV',
	FILM_DETAILS: 'FILM_DETAILS',

	/////////////Finder Store/////////////////
	SEARCH_FINDER: 'SEARCH_FINDER'
};
