export default {
  CREATE_USER: 'CREATE_USER',
  LOAD_USER: 'LOAD_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  UPDATE_USER: 'UPDATE_USER',
  LOAD_TEA_PRINCIPAL: 'LOAD_TEA_PRINCIPAL',
  LOAD_TEA_VARIETY: 'LOAD_TEA_VARIETY',
  CREATE_TEA_VARIETY: 'CREATE_TEA_VARIETY',
  UPDATE_TEA_VARIETY: 'UPDATE_TEA_VARIETY',
  DELETE_TEA_VARIETY: 'DELETE_TEA_VARIETY',
  LOAD_TEA_SEARCH: 'LOAD_TEA_SEARCH',
  LOAD_SHOP: 'LOAD_SHOP',
  CREATE_SHOP: 'CREATE_SHOP',
  DELETE_SHOP: 'DELETE_SHOP',
  UPDATE_SHOP: 'UPDATE_SHOP',
  LOAD_SHOP_SEARCH: 'LOAD_SHOP_SEARCH'
};
