export default {
    GET_QUESTION: 'GET_QUESTION',
    GET_THEMES: 'GET_THEMES',
    GET_TOP_THEMES: 'GET_TOP_THEMES',
    GET_LEADERBOARD: 'GET_LEADERBOARD',
    GET_SESSION_SET: 'GET_SESION_SET',
    GET_QUESTION_FROM_SESSION: 'GET_QUESTION_FROM_SESSION',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
}