export default {
    GET_QUESTION_ANSWER: 'GET_QUESTION_ANSWER',
    GET_QUESTION_OPTIONS: 'GET_QUESTION_OPTIONS',
    GET_QUESTION_TITLE: 'GET_QUESTION_TITLE',
    GET_QUESTION_RESULT: 'GET_QUESTION_RESULT',
    GET_THEMES: 'GET_THEMES',
    GET_TOP_THEMES: 'GET_TOP_THEMES',
    GET_LEADERBOARD: 'GET_LEADERBOARD'
}