const LIST_SKYLABERS = [
  { id: 1, name: "Martí" },
  { id: 2, name: "Olasz" },
  { id: 3, name: "Àlex" },
  { id: 4, name: "Gabriel" },
  { id: 5, name: "Dani" },
  { id: 6, name: "Aleix Sanllehi" },
  { id: 7, name: "Dani Alcalà" },
  { id: 8, name: "Esther Morillo" },
  { id: 9, name: "Fernando Valdivieso" },
  { id: 10, name: "Francesc Bruguerolas" },
  { id: 11, name: "Gemma Sanz" },
  { id: 12, name: "Gerard Ramon" },
  { id: 13, name: "Ramon Saura" },
  { id: 14, name: "Santiago Robinet" },
  { id: 15, name: "Vanessa Gómez" },
  { id: 16, name: "Anna" },
  { id: 17, name: "Jordi" },
  { id: 18, name: "Pablo Hortelano" },
  { id: 9, name: "Simón Besteiro" },
  { id: 20, name: "Víctor Alemany" },
];
console.log(LIST_SKYLABERS);
