export default {
	LOGIN_USER: 'LOGIN_USER',
	LOAD_USER_IMG: 'LOAD_USER_IMG',
	LOAD_REPO_LIST: 'LOAD_REPO_LIST',
	LOAD_GROUP: 'LOAD_GROUP',
	LOAD_REPO: 'LOAD_REPO',
	LOAD_COMMITS: 'LOAD_COMMITS',
	LOGIN: 'LOGIN',
	LOGIN_GITHUB: 'LOGIN_GITHUB',
	LOGOUT: 'LOGOUT'
};
