const ACTION_TYPES = {
    UPDATE_HERO: 'UPDATE_HERO',
    CREATE_HERO: 'CREATE_HERO',
    DELETE_HERO: 'DELETE_HERO',
    SEARCH_HERO: 'SEARCH_HERO',
    LOAD_HERO_BY_ID: 'LOAD_HERO_BY_ID',
    LOAD_HERO_BY_NAME: 'LOAD_HERO_BY_NAME',
    LOAD_HERO_LIST_FULL: 'LOAD_HERO_LIST_FULL',
    LOAD_HERO_LIST_PAGINATED: 'LOAD_HERO_LIST_PAGINATED',
    LOAD_HERO_LIST_TOP : 'LOAD_HERO_LIST_TOP'
}

exports.ACTION_TYPES = ACTION_TYPES;