export default {
  // SER ACTIONS
  CREATE_USER: "CREATE_USER",
  LOGIN_USER: "LOGIN_USER",
  CREATE_QUESTION: "CREATE_QUESTION",
  LOAD_VET_QUESTION: "LOAD_VET_QUESTION",
  // DETAIL ACTIONS

  CREATE_VET: "CREATE_VET",
  LOAD_VETS: "LOAD_VETS",
  LOAD_DETAIL_VETS: "LOAD_DETAIL_VETS",
};
