export default {
    LOAD_DETAIL: 'LOAD_DETAIL',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ERROR: 'ERROR',
    REGISTER: 'REGISTER',
    LOAD_ENTRIES: 'LOAD_ENTRIES',
    LOAD_COMMENTS: 'LOAD_COMMENTS',
    ADD_COMMENT: 'ADD_COMMENT',
    ADD_ENTRY: 'ADD_ENTRY',
    EDIT_USER: 'EDIT_USER'
};
