export default {
  LOAD_FEED: "LOAD_FEED",
  LOAD_AINGURA: "LOAD_AINGURA",
  CREATE_USER: "CREATE USER",
  LOGIN_USER: "LOGIN_USER",
  USER_EXISTS: "USER_EXISTS",
  LOAD_ONE_AINGURA: "LOAD_ONE_AINGURA",
  LOAD_PICTURES: "LOAD_PICTURES",
  VALIDATE_LOCATION: "VALIDATE LOCATION",
  REACH_AINGURA: "REACH_AINGURA",
};
