export default {
  LOAD_EVENTS: "LOAD_EVENTS",
  LOAD_EVENT: "LOAD_EVENT",
  CREATE_EVENT: "CREATE_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  JOIN_EVENT: "JOIN_EVENT",

  LOAD_USER: "LOAD_USER",
  CREATE_USER: "CREATE_USER",

  LOAD_GROUPS: "LOAD_GROUPS",
  UPDATE_GROUP: "UPDATE_GROUP",

  LOAD_LESSONS: "LOAD_LESSONS",
};
