export default {
	LOAD_CHAR: 'LOAD_CHAR_LIST',
	LOAD_SAGA_LIST: 'LOAD_SAGA_LIST',
	CREATE_PROFILE: 'CREATE_PROFILE',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	LOAD_PLANETS: 'LOAD_PLANETS',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	GLOBAL_SEARCH: 'GLOBAL_SEARCH',
	LOSS_INC: 'LOSS_INC',
	WIN_INC: 'WIN_INC'
};
