export default {
	CREATE_USER: 'CREATE_USER',
	LOAD_USER: 'LOAD_USER',
	UPDATE_USER: 'UPDATE_USER',
	//como seria mas correcto? SAVE USER PREFERENCE? O SAVE PREFERENCE?
	//SAVE_PREFERENCE: 'SAVE_PREFERENCE',
	LOAD_RECIPE: 'LOAD_RECIPE',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT'
};
