export default {
	LOAD_ALERTS: 'LOAD_ALERTS',
	CREATE_USER: 'CREATE_USER',
	LOAD_USER: 'LOAD_USER',
	UPDATE_USER: 'UPDATE_USER',
	CREATE_ALERT: 'CREATE_ALERT',
	LOAD_ALERT_BYID: 'LOAD_ALERT_BYID',
	LOAD_CATEGORIES:'LOAD_CATEGORIES',
	CLOSE_ALERT: 'CLOSE_ALERT',
	UPDATE_COMMENTS_ALERT: 'UPDATE_COMMENTS_ALERT',
	FOLLOW_ALERT: 'FOLLOW_ALERT'
};