export default {
  LOAD_SPOT: "LOAD_SPOT",
  CREATE_SPOT: "CREATE_SPOT",
  DELETE_SPOT: "DELETE_SPOT",
  LOGIN_USER: "LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  SIGNOUT_USER: "SIGNOUT_USER",
  SIGN_INVITATE: "SIGN_INVITATE",
  UPLOAD_SPOT_PHOTO: "UPLOAD_SPOT_PHOTO",
};
