export default {
  /** USER ACTIONS */
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  /** USER SETTINGS ACTIONS */
  LOAD_USER: "LOAD_USER",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  /** MAP ACTIONS */
  LOAD_SPOTS: "LOAD_SPOTS",
  CREATE_SPOT: "CREATE_SPOT",
  DESTROY_SPOT: "DESTROY_SPOT",

  /** PROFILE ACTIONS */
  LOAD_MAKES: "LOAD_MAKES",
  LOAD_MODELS: "LOAD_MODELS",
  SELECT_CAR: "SELECT_CAR",
};
