export default {
    CREATE_USER: 'CREATE_USER',
    LOAD_USER: 'LOAD_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_DETAIL_USER: 'LOAD_DETAIL_USER',
    LOAD_USERS: 'LOAD_USERS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CREATE_USER_DETAIL: 'CREATE_USER_DETAIL',
    GET_COORDINATES: 'GET_COORDINATES',
    UPDATE_USER_DETAIL: 'UPDATE_USER_DETAIL',
    LOAD_EMAILS: 'LOAD_EMAILS',
    LOAD_EMAIL: 'LOAD_EMAIL',
    CREATE_EMAIL: 'CREATE_EMAIL'
};