export default {
    CREATE_USER: "CREATE_USER",
    LOAD_USER: "LOAD_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",

    CREATE_STORE: "CREATE_STORE",
    LOAD_STORE_LIST: "LOAD_STORE_LIST",
    UPDATE_STORE: "UPDATE_STORE",
    DELETE_STORE: "DELETE_STORE",

    CREATE_PRODUCT: "CREATE_PRODUCT",
    LOAD_PRODUCT_LIST: "LOAD_PRODUCT_LIST",
    LOAD_PRODUCT: "LOAD_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    
    SEARCH_FINDER: "SEARCH_FINDER",
    ADD_CART: "ADD_CART",
    DELETE_CART: "DELETE_CART",
};